// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protocol_v3.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace App.Protocol {

  /// <summary>Holder for reflection information generated from Protocol_v3.proto</summary>
  public static partial class ProtocolV3Reflection {

    #region Descriptor
    /// <summary>File descriptor for Protocol_v3.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtocolV3Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFQcm90b2NvbF92My5wcm90bxIMYXBwLnByb3RvY29sIjYKClV0aWxpemF0",
            "b3ISCgoCaWQYASABKAUSDAoEdXNlchgCIAEoCRIOCgZwYXJvbGEYAyABKAki",
            "awoJSW5zY3JpZXJlEgoKAmlkGAEgASgFEi4KC3BhcnRpY2lwYW50GAIgASgL",
            "MhkuYXBwLnByb3RvY29sLlBhcnRpY2lwYW50EiIKBXByb2JhGAMgASgLMhMu",
            "YXBwLnByb3RvY29sLlByb2JhIjcKC1BhcnRpY2lwYW50EgoKAmlkGAEgASgF",
            "EgwKBG51bWUYAiABKAkSDgoGdmFyc3RhGAMgASgFIjMKBVByb2JhEgoKAmlk",
            "GAEgASgFEhAKCERpc3RhbnRhGAIgASgCEgwKBHN0aWwYAyABKAkirAMKB1Jl",
            "cXVlc3QSKAoEdHlwZRgBIAEoDjIaLmFwcC5wcm90b2NvbC5SZXF1ZXN0LlR5",
            "cGUSJgoEdXNlchgCIAEoCzIYLmFwcC5wcm90b2NvbC5VdGlsaXphdG9yEiIK",
            "BXByb2JhGAMgASgLMhMuYXBwLnByb3RvY29sLlByb2JhEi4KC3BhcnRpY2lw",
            "YW50GAQgASgLMhkuYXBwLnByb3RvY29sLlBhcnRpY2lwYW50EjEKDnBhcnRp",
            "Y2lwbmF0Tm91GAUgASgLMhkuYXBwLnByb3RvY29sLlBhcnRpY2lwYW50EiYK",
            "CWxpc3RQcm9iZRgGIAMoCzITLmFwcC5wcm90b2NvbC5Qcm9iYSKfAQoEVHlw",
            "ZRIKCgZVbmtvd24QABIJCgVMb2dpbhABEgoKBkxvZ291dBACEg0KCUdldF9Q",
            "cm9iZRADEh8KG0dldF9QYXJ0aWNpcGFudGlfRHVwYV9Qcm9iZRAEEh4KGkdl",
            "dF9Qcm9iZV9EdXBhX1BhcnRpY2lwYW50EAUSCwoHSW5zY3JpZRAGEhcKE0dl",
            "dF9Ocl9QYXJ0aWNpcGFudGkQByKFAwoIUmVzcG9uc2USKQoEdHlwZRgBIAEo",
            "DjIbLmFwcC5wcm90b2NvbC5SZXNwb25zZS5UeXBlEg0KBWVycm9yGAIgASgJ",
            "EiIKBXByb2JlGAMgAygLMhMuYXBwLnByb3RvY29sLlByb2JhEi8KDHBhcnRp",
            "Y2lwYW50aRgEIAMoCzIZLmFwcC5wcm90b2NvbC5QYXJ0aWNpcGFudBItChBw",
            "cm9iZVBhcnRpY2lwYW50GAUgAygLMhMuYXBwLnByb3RvY29sLlByb2JhEhYK",
            "Dm5yUGFydGljaXBuYXRpGAYgAygFIqIBCgRUeXBlEgsKB1Vua25vd24QABIG",
            "CgJPaxABEgkKBUVycm9yEAISDQoJR2V0X1Byb2JlEAMSHwobR2V0X1BhcnRp",
            "Y2lwYW50aV9EdXBhX1Byb2JlEAQSHgoaR2V0X1Byb2JlX0R1cGFfUGFydGlj",
            "aXBhbnQQBRIXChNHZXRfTnJfUGFydGljaXBhbnRpEAYSEQoNTmV3X0luc2Ny",
            "aWVyZRAHQiIKEXByb3RvYnVmZnByb3RvY29sQg1DaGF0UHJvdG9idWZzYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::App.Protocol.Utilizator), global::App.Protocol.Utilizator.Parser, new[]{ "Id", "User", "Parola" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::App.Protocol.Inscriere), global::App.Protocol.Inscriere.Parser, new[]{ "Id", "Participant", "Proba" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::App.Protocol.Participant), global::App.Protocol.Participant.Parser, new[]{ "Id", "Nume", "Varsta" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::App.Protocol.Proba), global::App.Protocol.Proba.Parser, new[]{ "Id", "Distanta", "Stil" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::App.Protocol.Request), global::App.Protocol.Request.Parser, new[]{ "Type", "User", "Proba", "Participant", "ParticipnatNou", "ListProbe" }, null, new[]{ typeof(global::App.Protocol.Request.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::App.Protocol.Response), global::App.Protocol.Response.Parser, new[]{ "Type", "Error", "Probe", "Participanti", "ProbeParticipant", "NrParticipnati" }, null, new[]{ typeof(global::App.Protocol.Response.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Utilizator : pb::IMessage<Utilizator>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Utilizator> _parser = new pb::MessageParser<Utilizator>(() => new Utilizator());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Utilizator> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::App.Protocol.ProtocolV3Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Utilizator() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Utilizator(Utilizator other) : this() {
      id_ = other.id_;
      user_ = other.user_;
      parola_ = other.parola_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Utilizator Clone() {
      return new Utilizator(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 2;
    private string user_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string User {
      get { return user_; }
      set {
        user_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "parola" field.</summary>
    public const int ParolaFieldNumber = 3;
    private string parola_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Parola {
      get { return parola_; }
      set {
        parola_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Utilizator);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Utilizator other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (User != other.User) return false;
      if (Parola != other.Parola) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (User.Length != 0) hash ^= User.GetHashCode();
      if (Parola.Length != 0) hash ^= Parola.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (User.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(User);
      }
      if (Parola.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Parola);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (User.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(User);
      }
      if (Parola.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Parola);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (User.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(User);
      }
      if (Parola.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Parola);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Utilizator other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.User.Length != 0) {
        User = other.User;
      }
      if (other.Parola.Length != 0) {
        Parola = other.Parola;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            User = input.ReadString();
            break;
          }
          case 26: {
            Parola = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            User = input.ReadString();
            break;
          }
          case 26: {
            Parola = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Inscriere : pb::IMessage<Inscriere>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Inscriere> _parser = new pb::MessageParser<Inscriere>(() => new Inscriere());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Inscriere> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::App.Protocol.ProtocolV3Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Inscriere() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Inscriere(Inscriere other) : this() {
      id_ = other.id_;
      participant_ = other.participant_ != null ? other.participant_.Clone() : null;
      proba_ = other.proba_ != null ? other.proba_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Inscriere Clone() {
      return new Inscriere(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "participant" field.</summary>
    public const int ParticipantFieldNumber = 2;
    private global::App.Protocol.Participant participant_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::App.Protocol.Participant Participant {
      get { return participant_; }
      set {
        participant_ = value;
      }
    }

    /// <summary>Field number for the "proba" field.</summary>
    public const int ProbaFieldNumber = 3;
    private global::App.Protocol.Proba proba_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::App.Protocol.Proba Proba {
      get { return proba_; }
      set {
        proba_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Inscriere);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Inscriere other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(Participant, other.Participant)) return false;
      if (!object.Equals(Proba, other.Proba)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (participant_ != null) hash ^= Participant.GetHashCode();
      if (proba_ != null) hash ^= Proba.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (participant_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Participant);
      }
      if (proba_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Proba);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (participant_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Participant);
      }
      if (proba_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Proba);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (participant_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Participant);
      }
      if (proba_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Proba);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Inscriere other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.participant_ != null) {
        if (participant_ == null) {
          Participant = new global::App.Protocol.Participant();
        }
        Participant.MergeFrom(other.Participant);
      }
      if (other.proba_ != null) {
        if (proba_ == null) {
          Proba = new global::App.Protocol.Proba();
        }
        Proba.MergeFrom(other.Proba);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            if (participant_ == null) {
              Participant = new global::App.Protocol.Participant();
            }
            input.ReadMessage(Participant);
            break;
          }
          case 26: {
            if (proba_ == null) {
              Proba = new global::App.Protocol.Proba();
            }
            input.ReadMessage(Proba);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            if (participant_ == null) {
              Participant = new global::App.Protocol.Participant();
            }
            input.ReadMessage(Participant);
            break;
          }
          case 26: {
            if (proba_ == null) {
              Proba = new global::App.Protocol.Proba();
            }
            input.ReadMessage(Proba);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Participant : pb::IMessage<Participant>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Participant> _parser = new pb::MessageParser<Participant>(() => new Participant());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Participant> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::App.Protocol.ProtocolV3Reflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Participant() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Participant(Participant other) : this() {
      id_ = other.id_;
      nume_ = other.nume_;
      varsta_ = other.varsta_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Participant Clone() {
      return new Participant(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "nume" field.</summary>
    public const int NumeFieldNumber = 2;
    private string nume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Nume {
      get { return nume_; }
      set {
        nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "varsta" field.</summary>
    public const int VarstaFieldNumber = 3;
    private int varsta_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Varsta {
      get { return varsta_; }
      set {
        varsta_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Participant);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Participant other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Nume != other.Nume) return false;
      if (Varsta != other.Varsta) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Nume.Length != 0) hash ^= Nume.GetHashCode();
      if (Varsta != 0) hash ^= Varsta.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (Varsta != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Varsta);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (Varsta != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Varsta);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Nume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
      }
      if (Varsta != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Varsta);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Participant other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Nume.Length != 0) {
        Nume = other.Nume;
      }
      if (other.Varsta != 0) {
        Varsta = other.Varsta;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 24: {
            Varsta = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 24: {
            Varsta = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Proba : pb::IMessage<Proba>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Proba> _parser = new pb::MessageParser<Proba>(() => new Proba());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Proba> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::App.Protocol.ProtocolV3Reflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Proba() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Proba(Proba other) : this() {
      id_ = other.id_;
      distanta_ = other.distanta_;
      stil_ = other.stil_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Proba Clone() {
      return new Proba(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "Distanta" field.</summary>
    public const int DistantaFieldNumber = 2;
    private float distanta_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Distanta {
      get { return distanta_; }
      set {
        distanta_ = value;
      }
    }

    /// <summary>Field number for the "stil" field.</summary>
    public const int StilFieldNumber = 3;
    private string stil_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Stil {
      get { return stil_; }
      set {
        stil_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Proba);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Proba other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Distanta, other.Distanta)) return false;
      if (Stil != other.Stil) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Distanta != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Distanta);
      if (Stil.Length != 0) hash ^= Stil.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Distanta != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Distanta);
      }
      if (Stil.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Stil);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Distanta != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Distanta);
      }
      if (Stil.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Stil);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Distanta != 0F) {
        size += 1 + 4;
      }
      if (Stil.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Stil);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Proba other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Distanta != 0F) {
        Distanta = other.Distanta;
      }
      if (other.Stil.Length != 0) {
        Stil = other.Stil;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 21: {
            Distanta = input.ReadFloat();
            break;
          }
          case 26: {
            Stil = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 21: {
            Distanta = input.ReadFloat();
            break;
          }
          case 26: {
            Stil = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::App.Protocol.ProtocolV3Reflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request(Request other) : this() {
      type_ = other.type_;
      user_ = other.user_ != null ? other.user_.Clone() : null;
      proba_ = other.proba_ != null ? other.proba_.Clone() : null;
      participant_ = other.participant_ != null ? other.participant_.Clone() : null;
      participnatNou_ = other.participnatNou_ != null ? other.participnatNou_.Clone() : null;
      listProbe_ = other.listProbe_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::App.Protocol.Request.Types.Type type_ = global::App.Protocol.Request.Types.Type.Unkown;
    /// <summary>
    /// Identifies which request is filled in.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::App.Protocol.Request.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 2;
    private global::App.Protocol.Utilizator user_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::App.Protocol.Utilizator User {
      get { return user_; }
      set {
        user_ = value;
      }
    }

    /// <summary>Field number for the "proba" field.</summary>
    public const int ProbaFieldNumber = 3;
    private global::App.Protocol.Proba proba_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::App.Protocol.Proba Proba {
      get { return proba_; }
      set {
        proba_ = value;
      }
    }

    /// <summary>Field number for the "participant" field.</summary>
    public const int ParticipantFieldNumber = 4;
    private global::App.Protocol.Participant participant_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::App.Protocol.Participant Participant {
      get { return participant_; }
      set {
        participant_ = value;
      }
    }

    /// <summary>Field number for the "participnatNou" field.</summary>
    public const int ParticipnatNouFieldNumber = 5;
    private global::App.Protocol.Participant participnatNou_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::App.Protocol.Participant ParticipnatNou {
      get { return participnatNou_; }
      set {
        participnatNou_ = value;
      }
    }

    /// <summary>Field number for the "listProbe" field.</summary>
    public const int ListProbeFieldNumber = 6;
    private static readonly pb::FieldCodec<global::App.Protocol.Proba> _repeated_listProbe_codec
        = pb::FieldCodec.ForMessage(50, global::App.Protocol.Proba.Parser);
    private readonly pbc::RepeatedField<global::App.Protocol.Proba> listProbe_ = new pbc::RepeatedField<global::App.Protocol.Proba>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::App.Protocol.Proba> ListProbe {
      get { return listProbe_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(User, other.User)) return false;
      if (!object.Equals(Proba, other.Proba)) return false;
      if (!object.Equals(Participant, other.Participant)) return false;
      if (!object.Equals(ParticipnatNou, other.ParticipnatNou)) return false;
      if(!listProbe_.Equals(other.listProbe_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::App.Protocol.Request.Types.Type.Unkown) hash ^= Type.GetHashCode();
      if (user_ != null) hash ^= User.GetHashCode();
      if (proba_ != null) hash ^= Proba.GetHashCode();
      if (participant_ != null) hash ^= Participant.GetHashCode();
      if (participnatNou_ != null) hash ^= ParticipnatNou.GetHashCode();
      hash ^= listProbe_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::App.Protocol.Request.Types.Type.Unkown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (user_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(User);
      }
      if (proba_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Proba);
      }
      if (participant_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Participant);
      }
      if (participnatNou_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ParticipnatNou);
      }
      listProbe_.WriteTo(output, _repeated_listProbe_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::App.Protocol.Request.Types.Type.Unkown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (user_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(User);
      }
      if (proba_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Proba);
      }
      if (participant_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Participant);
      }
      if (participnatNou_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ParticipnatNou);
      }
      listProbe_.WriteTo(ref output, _repeated_listProbe_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::App.Protocol.Request.Types.Type.Unkown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (user_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      if (proba_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Proba);
      }
      if (participant_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Participant);
      }
      if (participnatNou_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ParticipnatNou);
      }
      size += listProbe_.CalculateSize(_repeated_listProbe_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::App.Protocol.Request.Types.Type.Unkown) {
        Type = other.Type;
      }
      if (other.user_ != null) {
        if (user_ == null) {
          User = new global::App.Protocol.Utilizator();
        }
        User.MergeFrom(other.User);
      }
      if (other.proba_ != null) {
        if (proba_ == null) {
          Proba = new global::App.Protocol.Proba();
        }
        Proba.MergeFrom(other.Proba);
      }
      if (other.participant_ != null) {
        if (participant_ == null) {
          Participant = new global::App.Protocol.Participant();
        }
        Participant.MergeFrom(other.Participant);
      }
      if (other.participnatNou_ != null) {
        if (participnatNou_ == null) {
          ParticipnatNou = new global::App.Protocol.Participant();
        }
        ParticipnatNou.MergeFrom(other.ParticipnatNou);
      }
      listProbe_.Add(other.listProbe_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::App.Protocol.Request.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (user_ == null) {
              User = new global::App.Protocol.Utilizator();
            }
            input.ReadMessage(User);
            break;
          }
          case 26: {
            if (proba_ == null) {
              Proba = new global::App.Protocol.Proba();
            }
            input.ReadMessage(Proba);
            break;
          }
          case 34: {
            if (participant_ == null) {
              Participant = new global::App.Protocol.Participant();
            }
            input.ReadMessage(Participant);
            break;
          }
          case 42: {
            if (participnatNou_ == null) {
              ParticipnatNou = new global::App.Protocol.Participant();
            }
            input.ReadMessage(ParticipnatNou);
            break;
          }
          case 50: {
            listProbe_.AddEntriesFrom(input, _repeated_listProbe_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::App.Protocol.Request.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (user_ == null) {
              User = new global::App.Protocol.Utilizator();
            }
            input.ReadMessage(User);
            break;
          }
          case 26: {
            if (proba_ == null) {
              Proba = new global::App.Protocol.Proba();
            }
            input.ReadMessage(Proba);
            break;
          }
          case 34: {
            if (participant_ == null) {
              Participant = new global::App.Protocol.Participant();
            }
            input.ReadMessage(Participant);
            break;
          }
          case 42: {
            if (participnatNou_ == null) {
              ParticipnatNou = new global::App.Protocol.Participant();
            }
            input.ReadMessage(ParticipnatNou);
            break;
          }
          case 50: {
            listProbe_.AddEntriesFrom(ref input, _repeated_listProbe_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Request message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unkown")] Unkown = 0,
        [pbr::OriginalName("Login")] Login = 1,
        [pbr::OriginalName("Logout")] Logout = 2,
        [pbr::OriginalName("Get_Probe")] GetProbe = 3,
        [pbr::OriginalName("Get_Participanti_Dupa_Probe")] GetParticipantiDupaProbe = 4,
        [pbr::OriginalName("Get_Probe_Dupa_Participant")] GetProbeDupaParticipant = 5,
        [pbr::OriginalName("Inscrie")] Inscrie = 6,
        [pbr::OriginalName("Get_Nr_Participanti")] GetNrParticipanti = 7,
      }

    }
    #endregion

  }

  public sealed partial class Response : pb::IMessage<Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::App.Protocol.ProtocolV3Reflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response(Response other) : this() {
      type_ = other.type_;
      error_ = other.error_;
      probe_ = other.probe_.Clone();
      participanti_ = other.participanti_.Clone();
      probeParticipant_ = other.probeParticipant_.Clone();
      nrParticipnati_ = other.nrParticipnati_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::App.Protocol.Response.Types.Type type_ = global::App.Protocol.Response.Types.Type.Unknown;
    /// <summary>
    /// Identifies which request is filled in.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::App.Protocol.Response.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    /// <summary>
    /// One of the following will be filled in, depending on the type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "probe" field.</summary>
    public const int ProbeFieldNumber = 3;
    private static readonly pb::FieldCodec<global::App.Protocol.Proba> _repeated_probe_codec
        = pb::FieldCodec.ForMessage(26, global::App.Protocol.Proba.Parser);
    private readonly pbc::RepeatedField<global::App.Protocol.Proba> probe_ = new pbc::RepeatedField<global::App.Protocol.Proba>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::App.Protocol.Proba> Probe {
      get { return probe_; }
    }

    /// <summary>Field number for the "participanti" field.</summary>
    public const int ParticipantiFieldNumber = 4;
    private static readonly pb::FieldCodec<global::App.Protocol.Participant> _repeated_participanti_codec
        = pb::FieldCodec.ForMessage(34, global::App.Protocol.Participant.Parser);
    private readonly pbc::RepeatedField<global::App.Protocol.Participant> participanti_ = new pbc::RepeatedField<global::App.Protocol.Participant>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::App.Protocol.Participant> Participanti {
      get { return participanti_; }
    }

    /// <summary>Field number for the "probeParticipant" field.</summary>
    public const int ProbeParticipantFieldNumber = 5;
    private static readonly pb::FieldCodec<global::App.Protocol.Proba> _repeated_probeParticipant_codec
        = pb::FieldCodec.ForMessage(42, global::App.Protocol.Proba.Parser);
    private readonly pbc::RepeatedField<global::App.Protocol.Proba> probeParticipant_ = new pbc::RepeatedField<global::App.Protocol.Proba>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::App.Protocol.Proba> ProbeParticipant {
      get { return probeParticipant_; }
    }

    /// <summary>Field number for the "nrParticipnati" field.</summary>
    public const int NrParticipnatiFieldNumber = 6;
    private static readonly pb::FieldCodec<int> _repeated_nrParticipnati_codec
        = pb::FieldCodec.ForInt32(50);
    private readonly pbc::RepeatedField<int> nrParticipnati_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> NrParticipnati {
      get { return nrParticipnati_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Error != other.Error) return false;
      if(!probe_.Equals(other.probe_)) return false;
      if(!participanti_.Equals(other.participanti_)) return false;
      if(!probeParticipant_.Equals(other.probeParticipant_)) return false;
      if(!nrParticipnati_.Equals(other.nrParticipnati_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::App.Protocol.Response.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      hash ^= probe_.GetHashCode();
      hash ^= participanti_.GetHashCode();
      hash ^= probeParticipant_.GetHashCode();
      hash ^= nrParticipnati_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::App.Protocol.Response.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      probe_.WriteTo(output, _repeated_probe_codec);
      participanti_.WriteTo(output, _repeated_participanti_codec);
      probeParticipant_.WriteTo(output, _repeated_probeParticipant_codec);
      nrParticipnati_.WriteTo(output, _repeated_nrParticipnati_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::App.Protocol.Response.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      probe_.WriteTo(ref output, _repeated_probe_codec);
      participanti_.WriteTo(ref output, _repeated_participanti_codec);
      probeParticipant_.WriteTo(ref output, _repeated_probeParticipant_codec);
      nrParticipnati_.WriteTo(ref output, _repeated_nrParticipnati_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::App.Protocol.Response.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      size += probe_.CalculateSize(_repeated_probe_codec);
      size += participanti_.CalculateSize(_repeated_participanti_codec);
      size += probeParticipant_.CalculateSize(_repeated_probeParticipant_codec);
      size += nrParticipnati_.CalculateSize(_repeated_nrParticipnati_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::App.Protocol.Response.Types.Type.Unknown) {
        Type = other.Type;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      probe_.Add(other.probe_);
      participanti_.Add(other.participanti_);
      probeParticipant_.Add(other.probeParticipant_);
      nrParticipnati_.Add(other.nrParticipnati_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::App.Protocol.Response.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            probe_.AddEntriesFrom(input, _repeated_probe_codec);
            break;
          }
          case 34: {
            participanti_.AddEntriesFrom(input, _repeated_participanti_codec);
            break;
          }
          case 42: {
            probeParticipant_.AddEntriesFrom(input, _repeated_probeParticipant_codec);
            break;
          }
          case 50:
          case 48: {
            nrParticipnati_.AddEntriesFrom(input, _repeated_nrParticipnati_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::App.Protocol.Response.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            probe_.AddEntriesFrom(ref input, _repeated_probe_codec);
            break;
          }
          case 34: {
            participanti_.AddEntriesFrom(ref input, _repeated_participanti_codec);
            break;
          }
          case 42: {
            probeParticipant_.AddEntriesFrom(ref input, _repeated_probeParticipant_codec);
            break;
          }
          case 50:
          case 48: {
            nrParticipnati_.AddEntriesFrom(ref input, _repeated_nrParticipnati_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Response message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Ok")] Ok = 1,
        [pbr::OriginalName("Error")] Error = 2,
        [pbr::OriginalName("Get_Probe")] GetProbe = 3,
        [pbr::OriginalName("Get_Participanti_Dupa_Probe")] GetParticipantiDupaProbe = 4,
        [pbr::OriginalName("Get_Probe_Dupa_Participant")] GetProbeDupaParticipant = 5,
        [pbr::OriginalName("Get_Nr_Participanti")] GetNrParticipanti = 6,
        [pbr::OriginalName("New_Inscriere")] NewInscriere = 7,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
